{% set version = "1.900.31" %}

package:
  name: jasper
  version: {{ version }}

source:
  url: https://github.com/mdadams/jasper/archive/version-1.900.31.tar.gz
  sha256: 0099084dce9fa0a318b48a5ed2a12ac7cff3324f3fd4459833e6fe2ff583fb2c

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # no info.  Leaving at default behavior.
    - {{ pin_subpackage('jasper') }}

requirements:
  build:
    - {{ compiler('c') }}
    - automake             # [unix]
    - autoconf             # [unix]
    - libtool              # [unix]
    - make                 # [unix]
  host:
    - jpeg
  run:
    - jpeg

test:
  commands:
    - jasper --version
    - conda inspect linkages -p $PREFIX jasper  # [not win]
    - conda inspect objects -p $PREFIX jasper  # [osx]

about:
  home: http://www.ece.uvic.ca/~frodo/jasper/
  license: JasPer 2.0
  license_file: LICENSE
  summary: 'A reference implementation of the codec specified in the JPEG-2000 Part-1 standard.'

extra:
  recipe-maintainers:
    - jakirkham
    - jhamman
    - ocefpaf
