# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "INN4eJx5JJtS8op9DzskiQ+HSAGBu2L1jkHMONTQZgANLVxMWmNmonCkJY1QdfvA7VsWOSJyudpHCHVCoqlRyK7W7KLO9PLHLl+gKqTaBsaEZtVRMOphcO5TXj3zzot3WgsJ5DnBRCCgfNaV1HAkMspqPAk5gA+huD4NP6rpEi12Cw2kXZe/mX8+yrj4FzhW+X/GkhFymNZDRVY0zdB/czfQGvy3+vdcnkjkSciUElUtGzs17587DGp1mPyrTZYOTrolFJ4WqIpJFgmL8rdsQ5kDs870sphiHe7BURSZ1UC5KpmBwkLSVzCOCbLNNng6qhyFCx70VIfQtphy412hUa8ap98pR9gc63pAFn0/cP1EG1EkZY8IncmjH9WVB5/xGei7+4VlJn9loqb0VOjlLzQcdOweoUJohsQQZTT/29LT3Br5aVL/cPlPT+d+KVz4Rwn01mcmlP6dsKKDXyVmWnWOr0mSSwMOAaW5ax60zl8lhzU7MCciUFNTJIbouno+Zu6XBeZL/Nx9Qa59lcZv5OwzELy8FZ/pe9zXdRG8NCEX82HsXPqv7a+Lp8AAKvVOFNAnUtlSLAVa5tI1G6zb+ShTvMHPy2lBt9w6VAHW9NkTHHg+e+/Ae4ll6GrDNGwy5sIH176Ye8TpDQEsbq5rtZ+FmQgvzUCI71UkRXlLNlM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
