appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: INN4eJx5JJtS8op9DzskiQ+HSAGBu2L1jkHMONTQZgANLVxMWmNmonCkJY1QdfvA7VsWOSJyudpHCHVCoqlRyK7W7KLO9PLHLl+gKqTaBsaEZtVRMOphcO5TXj3zzot3WgsJ5DnBRCCgfNaV1HAkMspqPAk5gA+huD4NP6rpEi12Cw2kXZe/mX8+yrj4FzhW+X/GkhFymNZDRVY0zdB/czfQGvy3+vdcnkjkSciUElUtGzs17587DGp1mPyrTZYOTrolFJ4WqIpJFgmL8rdsQ5kDs870sphiHe7BURSZ1UC5KpmBwkLSVzCOCbLNNng6qhyFCx70VIfQtphy412hUa8ap98pR9gc63pAFn0/cP1EG1EkZY8IncmjH9WVB5/xGei7+4VlJn9loqb0VOjlLzQcdOweoUJohsQQZTT/29LT3Br5aVL/cPlPT+d+KVz4Rwn01mcmlP6dsKKDXyVmWnWOr0mSSwMOAaW5ax60zl8lhzU7MCciUFNTJIbouno+Zu6XBeZL/Nx9Qa59lcZv5OwzELy8FZ/pe9zXdRG8NCEX82HsXPqv7a+Lp8AAKvVOFNAnUtlSLAVa5tI1G6zb+ShTvMHPy2lBt9w6VAHW9NkTHHg+e+/Ae4ll6GrDNGwy5sIH176Ye8TpDQEsbq5rtZ+FmQgvzUCI71UkRXlLNlM=}
conda_forge_output_validation: true
